Repository EnergyModelsX/EnergyModelsGeography.jl, pull requests merged in 2024-08, with the labels that each got.

#24 Fix bug on variable OPEX
  .github/workflows/ci.yml
  NEWS.md
  Project.toml
  src/constraint_functions.jl
Labels: bug

#25 Fix bug on variable OPEX
  .github/workflows/ci.yml
  NEWS.md
  Project.toml
  src/constraint_functions.jl
Labels: bug

#23 Support EMB-independent EMI
  NEWS.md
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/how-to/contribute.md
  docs/src/index.md
  docs/src/library/internals/reference_EMIExt.md
  docs/src/library/public.md
  docs/src/manual/constraint-functions.md
  docs/src/manual/investments.md
  docs/src/manual/optimization-variables.md
  docs/src/manual/philosophy.md
  docs/src/manual/quick-start.md
  docs/src/manual/simple-example.md
  docs/src/manual/transmission-mode.md
  examples/Project.toml
  examples/investments.jl
  ext/EMIExt/EMIExt.jl
  ext/EMIExt/legacy_constructor.jl
  ext/EMIExt/model.jl
  ext/EMIExt/utils.jl
  src/EnergyModelsGeography.jl
  src/structures/data.jl
  test/test_examples.jl
  test/test_investments.jl
Labels: enhancement

#26 Inclusion of potential for `TransmissionMode` emissions
  NEWS.md
  src/constraint_functions.jl
  src/model.jl
  src/structures/mode.jl
Labels: enhancement

#27 Improvement of types `PipeSimple` and `PipeLinepackSimple`
  NEWS.md
  docs/make.jl
  docs/src/how-to/update-models.md
  docs/src/index.md
  docs/src/library/public.md
  src/constraint_functions.jl
  src/legacy_constructors.jl
  src/model.jl
  src/structures/mode.jl
  test/test_geo_unidirectional.jl
  test/test_simplelinepack.jl
  test/test_simplepipe.jl
Labels: enhancement

#28 Fixed NEWS.md date
  NEWS.md
Labels: documentation
